# Generated by Django 4.2 on 2023-04-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cnie',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='ppr',
            field=models.PositiveIntegerField(),
        ),
    ]
