# Generated by Django 4.2 on 2023-04-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_reunion_alter_projetuser_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='start_time',
            field=models.DateField(),
        ),
    ]
