# Generated by Django 4.2 on 2023-04-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_reunion_end_time_alter_reunion_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
