# Generated by Django 4.2 on 2023-04-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_reunion_end_time_alter_reunion_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reunion',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='reunion',
            name='start_time',
            field=models.CharField(max_length=500),
        ),
    ]
