# Generated by Django 4.2 on 2023-04-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_reunion_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reunion',
            old_name='start_time',
            new_name='start',
        ),
    ]
