# Generated by Django 4.2 on 2023-04-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_start_time_reunion_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
