# Generated by Django 4.2 on 2023-04-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_reunion_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion',
            name='start',
            field=models.CharField(max_length=500),
        ),
    ]
