# Generated by Django 4.2 on 2023-04-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_reunion_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='end',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
