# Generated by Django 4.2 on 2023-05-03 15:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_reunion_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule_programme', models.CharField(max_length=900)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('cout_global', models.PositiveIntegerField()),
                ('nombre_projets', models.PositiveIntegerField()),
                ('observation', models.CharField(max_length=999)),
            ],
        ),
        migrations.RemoveField(
            model_name='projet',
            name='cout_actualise',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='cout_actualise_currency',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='cout_initial',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='cout_initial_currency',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='credit_engage',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='credit_engage_currency',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='date_achevement',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='date_debut_trav_effective',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='delai_realisation',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='intitule',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='paiements',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='paiements_currency',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='partenaires',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='secteur',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='status_etudes',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='status_projet',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='volet_stratigique',
        ),
        migrations.AddField(
            model_name='projet',
            name='budget_global',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projet',
            name='date_debut_previsionnelle',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='date_debut_reel',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='date_fin_previsionnelle',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='date_fin_reel',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='engagemet',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='intitule_projet',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='moa',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='moad',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='observation',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='paiement',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='statue_etude',
            field=models.CharField(choices=[('Aucun', 'Aucun'), ('Planifie', 'Planifie'), ('En cours', 'En cours'), ('Achevée', 'Achevée')], default='Aucun', max_length=90),
        ),
        migrations.AddField(
            model_name='projet',
            name='statue_projet',
            field=models.CharField(choices=[('Planifie', 'Planifie'), ('En cours', 'En cours'), ('Achevée', 'Achevée')], default='Planifie', max_length=90),
        ),
        migrations.AddField(
            model_name='projet',
            name='taux_davancement',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='projet',
            name='localisation',
            field=models.CharField(max_length=1000),
        ),
        migrations.AddField(
            model_name='projet',
            name='programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.programme'),
        ),
    ]
