# Generated by Django 4.2 on 2023-05-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_programme_remove_projet_cout_actualise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='observation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='observation',
            field=models.TextField(null=True),
        ),
    ]
