# Generated by Django 4.2 on 2023-05-08 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_programme_observation_alter_projet_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
