# Generated by Django 4.2 on 2023-05-09 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_projet_users_delete_projetuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='users',
        ),
        migrations.AddField(
            model_name='programme',
            name='users',
            field=models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projet',
            name='secteur',
            field=models.CharField(choices=[('Tourisme', 'Tourisme'), ('Culture', 'Culture'), ('Sport', 'Sport'), ('Agriculture', 'Agriculture'), ('Economie sociale', 'Economie sociale')], default='Tourisme', max_length=90),
        ),
        migrations.AlterField(
            model_name='projet',
            name='statue_etude',
            field=models.CharField(choices=[('Aucun', 'Aucun'), ('Planifié', 'Planifié'), ('En cours', 'En cours'), ('Achevée', 'Achevée')], default='Aucun', max_length=90),
        ),
        migrations.AlterField(
            model_name='projet',
            name='statue_projet',
            field=models.CharField(choices=[('Planifié', 'Planifié'), ('En cours', 'En cours'), ('Achevée', 'Achevée')], default='Planifié', max_length=90),
        ),
    ]
