# Generated by Django 4.2 on 2023-05-09 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_projet_users_programme_users_projet_secteur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution', models.DecimalField(decimal_places=2, max_digits=8)),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.partenaire')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.projet')),
            ],
        ),
        migrations.AddField(
            model_name='partenaire',
            name='projets',
            field=models.ManyToManyField(through='myapp.Participation', to='myapp.projet'),
        ),
    ]
