# Generated by Django 4.2 on 2023-05-11 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_participation_contribution_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('partenaire', 'projet')},
        ),
    ]
