# Generated by Django 4.2 on 2023-05-11 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_user_cnie_remove_user_date_recrutement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='genre',
        ),
    ]
