# Generated by Django 4.2 on 2023-05-15 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_user_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='engagemet',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projet',
            name='statue_projet',
            field=models.CharField(choices=[('En cours de démarrage', 'En cours de démarrage'), ('Planifié', 'Planifié'), ('En cours de réalisation', 'En cours de réalisation'), ('Achevée', 'Achevée')], default='Planifié', max_length=90),
        ),
        migrations.AlterField(
            model_name='projet',
            name='taux_davancement',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
