# Generated by Django 4.2 on 2023-05-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_projet_engagemet_alter_projet_statue_projet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='division',
            field=models.CharField(choices=[('DRINDH', 'DRINDH'), ('DESM', 'DESM'), ('DRCT', 'DRCT'), ('DCS', 'DCS')], default='DSIC', max_length=9),
        ),
    ]
