# Generated by Django 4.2 on 2023-05-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_user_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='statue_projet',
            field=models.CharField(choices=[('En cours de démarrage', 'En cours de démarrage'), ('Planifié', 'Planifié'), ('En cours de réalisation', 'En cours de réalisation'), ('Achevée', 'Achevée')], default='En cours de démarrage', max_length=90),
        ),
        migrations.AlterField(
            model_name='user',
            name='division',
            field=models.CharField(choices=[('DRINDH', 'DRINDH'), ('DESM', 'DESM'), ('DRCT', 'DRCT'), ('DCS', 'DCS')], default='DCS', max_length=9),
        ),
    ]
