# Generated by Django 4.2 on 2023-05-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_projet_statue_projet_alter_user_division'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programme',
            old_name='observation',
            new_name='observation_programme',
        ),
    ]
