# Generated by Django 4.2 on 2023-05-22 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_rename_observation_programme_observation_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
